### ISSUE TITLE
Default load orderbook for MLN/WETH asset pair

### ISSUE THREAD

**Issue by jennazenk** [avantgardefinance/interface#173]
When I go on the Trade page of my fund, there is no orderbook loaded by default. We should by default load the MLN/WETH orderbook

**Comment by fubhy** [comment]
That orderbook is actually loaded by default. It's just empty.

**Comment by fubhy** [comment]
It defaults to the first token that is not WETH: https://github.com/avantgardefinance/interface/blob/master/src/components/Routes/Fund/FundRoutes/FundTrade/FundTrading/FundOrderbookTrading/FundOrderbookTrading.tsx#L25

And that is MLN in our mainnet deployment file: https://github.com/avantgardefinance/interface/blob/master/deployments/mainnet-deployment.json#L85-L88

So by default it selected the MLN/WETH orderbook but since we don't show 0x orders at the moment (haven't added one of the remaining v2 SRA relayers yet) that's simply empty becuase there are no OasisDex orders for that.

**Comment by jennazenk** [comment]
In that case let’s make it default to something that has an orderbook otherwise it looks off

**Comment by fubhy** [comment]
Ok. So DAI would be an option here. Would that work? We should also limit the orderbook length. What is a good size limit there? 20 rows?

Or, instead of going with another pair, let's just add one of the v2 SRA relayer that still work?

**Comment by jennazenk** [comment]
Either are ok for me (default DAI/WETH, or use one of the remaining relayer on v2).  
We can try with size limit 20 rows and see how that looks

**Comment by fubhy** [comment]
Defaulting to DAI/WETH and limited size to 20. Adding one of the relayers is not good enough because they are mostly empty it seems.
